language: node_js

node_js:
  - "9"

env:
  global:
    - CC_TEST_REPORTER_ID=1c4feae9a685078726b61358fc7145f29761f877f1a8e5f2538d593dea207a89
    - CXX=g++-5
    - NODE_ENV=test

install:
  - npm install

before_script:
  - chmod 0755 ./node_modules/.bin/mocha
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test

deploy:
  skip_cleanup: true

after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT